export default {
  Backquote: {
    en: { normal: '`', shift: '~' },
    ru: { normal: 'ё', shift: 'Ё' },
  },
  Digit1: { en: { normal: '1', shift: '!' }, ru: { normal: '1', shift: '!' } },
  Digit2: { en: { normal: '2', shift: '@' }, ru: { normal: '2', shift: '"' } },
  Digit3: { en: { normal: '3', shift: '#' }, ru: { normal: '3', shift: '№' } },
  Digit4: { en: { normal: '4', shift: '$' }, ru: { normal: '4', shift: ';' } },
  Digit5: { en: { normal: '5', shift: '%' }, ru: { normal: '5', shift: '%' } },
  Digit6: { en: { normal: '6', shift: '^' }, ru: { normal: '6', shift: ':' } },
  Digit7: { en: { normal: '7', shift: '&' }, ru: { normal: '7', shift: '?' } },
  Digit8: { en: { normal: '8', shift: '*' }, ru: { normal: '8', shift: '*' } },
  Digit9: { en: { normal: '9', shift: '(' }, ru: { normal: '9', shift: '(' } },
  Digit0: { en: { normal: '0', shift: ')' }, ru: { normal: '0', shift: ')' } },
  Minus: { en: { normal: '-', shift: '_' }, ru: { normal: '-', shift: '_' } },
  Equal: { en: { normal: '=', shift: '+' }, ru: { normal: '=', shift: '+' } },
  Backspace: 'Backspace',
  Tab: 'Tab',
  KeyQ: { en: { normal: 'q', shift: 'Q' }, ru: { normal: 'й', shift: 'Й' } },
  KeyW: { en: { normal: 'w', shift: 'W' }, ru: { normal: 'ц', shift: 'Ц' } },
  KeyE: { en: { normal: 'e', shift: 'E' }, ru: { normal: 'у', shift: 'У' } },
  KeyR: { en: { normal: 'r', shift: 'R' }, ru: { normal: 'к', shift: 'К' } },
  KeyT: { en: { normal: 't', shift: 'T' }, ru: { normal: 'е', shift: 'Е' } },
  KeyY: { en: { normal: 'y', shift: 'Y' }, ru: { normal: 'н', shift: 'Н' } },
  KeyU: { en: { normal: 'u', shift: 'U' }, ru: { normal: 'г', shift: 'Г' } },
  KeyI: { en: { normal: 'i', shift: 'I' }, ru: { normal: 'ш', shift: 'Ш' } },
  KeyO: { en: { normal: 'o', shift: 'O' }, ru: { normal: 'щ', shift: 'Щ' } },
  KeyP: { en: { normal: 'p', shift: 'P' }, ru: { normal: 'з', shift: 'З' } },
  BracketLeft: {
    en: { normal: '[', shift: '}' },
    ru: { normal: 'х', shift: 'Х' },
  },
  BracketRight: {
    en: { normal: ']', shift: '}' },
    ru: { normal: 'ъ', shift: 'Ъ' },
  },
  Backslash: {
    en: { normal: '\\', shift: '|' },
    ru: { normal: '\\', shift: '/' },
  },
  Delete: 'Del',
  CapsLock: 'Caps Lock',
  KeyA: { en: { normal: 'a', shift: 'A' }, ru: { normal: 'ф', shift: 'Ф' } },
  KeyS: { en: { normal: 's', shift: 'S' }, ru: { normal: 'ы', shift: 'Ы' } },
  KeyD: { en: { normal: 'd', shift: 'D' }, ru: { normal: 'в', shift: 'В' } },
  KeyF: { en: { normal: 'f', shift: 'F' }, ru: { normal: 'а', shift: 'А' } },
  KeyG: { en: { normal: 'g', shift: 'G' }, ru: { normal: 'п', shift: 'П' } },
  KeyH: { en: { normal: 'h', shift: 'H' }, ru: { normal: 'р', shift: 'Р' } },
  KeyJ: { en: { normal: 'j', shift: 'J' }, ru: { normal: 'о', shift: 'О' } },
  KeyK: { en: { normal: 'k', shift: 'K' }, ru: { normal: 'л', shift: 'Л' } },
  KeyL: { en: { normal: 'l', shift: 'L' }, ru: { normal: 'д', shift: 'Д' } },
  Semicolon: {
    en: { normal: ';', shift: ':' },
    ru: { normal: 'ж', shift: 'Ж' },
  },
  Quote: { en: { normal: "'", shift: '"' }, ru: { normal: 'э', shift: 'Э' } },
  Enter: 'Enter',
  ShiftLeft: 'Shift',
  KeyZ: { en: { normal: 'z', shift: 'Z' }, ru: { normal: 'я', shift: 'Я' } },
  KeyX: { en: { normal: 'x', shift: 'X' }, ru: { normal: 'ч', shift: 'Ч' } },
  KeyC: { en: { normal: 'c', shift: 'C' }, ru: { normal: 'с', shift: 'С' } },
  KeyV: { en: { normal: 'v', shift: 'V' }, ru: { normal: 'м', shift: 'М' } },
  KeyB: { en: { normal: 'b', shift: 'B' }, ru: { normal: 'и', shift: 'И' } },
  KeyN: { en: { normal: 'n', shift: 'N' }, ru: { normal: 'т', shift: 'Т' } },
  KeyM: { en: { normal: 'm', shift: 'M' }, ru: { normal: 'ь', shift: 'Ь' } },
  Comma: { en: { normal: ',', shift: '<' }, ru: { normal: 'б', shift: 'Б' } },
  Period: { en: { normal: '.', shift: '>' }, ru: { normal: 'ю', shift: 'Ю' } },
  Slash: { en: { normal: '/', shift: '?' }, ru: { normal: '.', shift: ',' } },
  ArrowUp: '&#9650',
  ShiftRight: 'Shift',
  ControlLeft: 'Ctrl',
  MetaLeft: 'Win',
  AltLeft: 'Alt',
  Space: 'Space',
  AltRight: 'Alt',
  ArrowLeft: '◀',
  ArrowDown: '&#9660',
  ArrowRight: '▶',
  ControlRight: 'Ctrl',
};

// ArrowUp: ['↑', '↑', '↑', '↑'],
// ArrowLeft: ['←', '←', '←', '←'],
// ArrowDown: ['↓', '↓', '↓', '↓'],
// ArrowRight: ['→', '→', '→', '→'],
